using BillsMinimalApi.Dtos;
using BillsMinimalApi.Models;

namespace BillsMinimalApi.Mappers;

public static class BillMapper
{
    public static BillDto ToDto(Bill entity) => new()
    {
        Id = entity.Id,
        PayeeName = entity.PayeeName,
        DueDate = entity.DueDate,
        PaymentDue = entity.PaymentDue,
        Paid = entity.Paid,
        Version = entity.Version
    };

    /// <summary>
    /// Maps a DTO onto a brand-new entity, deliberately ignoring
    /// <see cref="BillDto.Id"/>. Postgres identity columns are
    /// GENERATED BY DEFAULT, so an explicit client-supplied Id is accepted
    /// silently and leaves the sequence behind it — every later insert then
    /// fails on a duplicate key once the sequence catches up.
    /// <see cref="Bill.Version"/> is likewise server-owned and stamped in
    /// <c>AppDbContext.StampAuditFields</c>.
    /// </summary>
    public static Bill ToNewEntity(BillDto dto) => new()
    {
        PayeeName = dto.PayeeName,
        DueDate = dto.DueDate,
        PaymentDue = dto.PaymentDue,
        Paid = dto.Paid
    };
}
