using BillsMinimalApi.Data;
using BillsMinimalApi.Dtos;
using BillsMinimalApi.Models;

namespace BillsMinimalApi.Mappers;

public static class BillMapper
{
    public static BillDto ToDto(Bill entity) => new()
    {
        Id = entity.Id,
        PayeeName = entity.PayeeName,
        DueDate = entity.DueDate,
        PaymentDue = entity.PaymentDue,
        Paid = entity.Paid,
        Version = entity.Version
    };

    /// <summary>
    /// Maps a DTO onto a brand-new entity, deliberately ignoring
    /// <see cref="BillDto.Id"/>. Postgres identity columns are
    /// GENERATED BY DEFAULT, so — unlike SQL Server IDENTITY — an explicit
    /// client-supplied Id is accepted silently and leaves the sequence behind
    /// it; every later insert then fails on a duplicate key once the sequence
    /// catches up. <see cref="Bill.Version"/> is likewise server-owned and
    /// stamped in <c>AppDbContext.StampAuditFields</c>.
    /// </summary>
    public static Bill ToNewEntity(BillDto dto)
    {
        var entity = new Bill();
        ApplyEditableFields(dto, entity);
        return entity;
    }

    /// <summary>
    /// Copies the client-editable fields onto an existing entity. Shared by POST
    /// and PUT so the two can never drift apart on which fields a client owns.
    /// <para>
    /// <see cref="Bill.DueDate"/> is normalised to UTC here rather than left to
    /// the DbContext value converter alone, so the entity held in memory matches
    /// what is stored. Without this the object returned from POST/PUT serialises
    /// as "2026-03-15T00:00:00" while a subsequent GET of the same bill returns
    /// "2026-03-15T00:00:00Z".
    /// </para>
    /// </summary>
    public static void ApplyEditableFields(BillDto dto, Bill entity)
    {
        entity.PayeeName = dto.PayeeName;
        entity.DueDate = UtcDateTime.Normalize(dto.DueDate);
        entity.PaymentDue = dto.PaymentDue;
        entity.Paid = dto.Paid;
    }
}
