using System.Net;
using System.Net.Http.Json;
using BillsMinimalApi.Dtos;

namespace BillsMinimalApi.Tests;

public class CreateBillTests : ApiTestBase
{
    public CreateBillTests(PostgresApiFixture fixture) : base(fixture)
    {
    }

    [Fact]
    public async Task Post_returns_201_with_a_Location_header_pointing_at_the_new_bill()
    {
        var response = await Client.PostAsJsonAsync(Routes.Bills, new BillDto
        {
            PayeeName = "Acme Corp",
            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc),
            PaymentDue = 42.50m,
        });

        Assert.Equal(HttpStatusCode.Created, response.StatusCode);

        var created = await response.Content.ReadFromJsonAsync<BillDto>();

        Assert.True(created!.Id > 0);
        Assert.Equal($"{Routes.Bills}/{created.Id}", response.Headers.Location?.ToString());

        // The Location header has to actually resolve, not just look right.
        var followed = await Client.GetAsync(response.Headers.Location);
        Assert.Equal(HttpStatusCode.OK, followed.StatusCode);
    }

    /// <summary>
    /// Regression guard for the audit-stamping bug: only the synchronous
    /// SaveChanges was overridden while every endpoint calls SaveChangesAsync,
    /// so CreateTime and Version were never written.
    /// </summary>
    [Fact]
    public async Task Post_stamps_CreateTime_and_starts_Version_at_1()
    {
        var before = DateTime.UtcNow.AddSeconds(-5);

        var created = await Fixture.CreateBillAsync();

        Assert.Equal(1, created.Version);

        var entity = await Fixture.ReadEntityAsync(created.Id);

        Assert.NotNull(entity);
        Assert.Equal(1, entity!.Version);
        Assert.InRange(entity.CreateTime, before, DateTime.UtcNow.AddSeconds(5));
        Assert.Equal(DateTimeKind.Utc, entity.CreateTime.Kind);
        Assert.Null(entity.UpdateTime);
    }

    /// <summary>
    /// Guard for the identity-sequence bug. Postgres identity columns are
    /// GENERATED BY DEFAULT, so — unlike SQL Server IDENTITY — an explicit
    /// client-supplied Id is accepted silently and leaves the sequence behind it.
    /// The second POST is the half that matters: it is the one that used to fail
    /// on a duplicate key once the sequence caught up.
    /// </summary>
    [Fact]
    public async Task Post_ignores_a_client_supplied_Id_and_leaves_the_sequence_intact()
    {
        var response = await Client.PostAsJsonAsync(Routes.Bills, new BillDto
        {
            Id = 500,
            PayeeName = "Sequence Squatter",
            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc),
            PaymentDue = 10m,
        });

        Assert.Equal(HttpStatusCode.Created, response.StatusCode);

        var first = await response.Content.ReadFromJsonAsync<BillDto>();
        Assert.NotEqual(500, first!.Id);
        Assert.Equal(1, first.Id);

        var second = await Fixture.CreateBillAsync("Follow Up");
        Assert.Equal(2, second.Id);

        // And nothing landed at the id the client asked for.
        var squatted = await Client.GetAsync($"{Routes.Bills}/500");
        Assert.Equal(HttpStatusCode.NotFound, squatted.StatusCode);
    }

    /// <summary>
    /// Version is server-owned in the same way Id is.
    /// </summary>
    [Fact]
    public async Task Post_ignores_a_client_supplied_Version()
    {
        var response = await Client.PostAsJsonAsync(Routes.Bills, new BillDto
        {
            PayeeName = "Version Squatter",
            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc),
            PaymentDue = 10m,
            Version = 99,
        });

        var created = await response.Content.ReadFromJsonAsync<BillDto>();

        Assert.Equal(1, created!.Version);
    }
}
